### ISSUE TITLE
data

### ISSUE THREAD

**Issue by persuelx** [KAI-yq/camera_lidar_fusion#1]
你好，能提供下你的测试bag包吗

**Comment by KAI-yq** [comment]
我手上没有bag包了，之前在学校做的，后面数据都没带走，不好意思哈

**Comment by KAI-yq** [comment]
> 你好，能提供下你的测试bag包吗

刚刚找到了硬盘里还有一个小bag，不知道能不能用，怎么给你呀，2.7g

**Comment by persuelx** [comment]
你上传到百度网盘链接再分享给我吧，谢谢

**Comment by KAI-yq** [comment]
> 你上传到百度网盘链接再分享给我吧，谢谢

你打开文叔叔，用后面这个取件码就可以取了，24小时有效，取件码：rmxxh。

**Comment by persuelx** [comment]
显示无效的取件码。。一般没怎么用文叔叔，是不是这个原因导致的

**Comment by KAI-yq** [comment]
> 显示无效的取件码。。一般没怎么用文叔叔，是不是这个原因导致的

https://t.wss.ink/f/aive7m31j7i  用这个链接试试吧
